branches:
  only:
  - src
language: python
python:
- '2.7'
before_install:
- npm install -g grunt-cli
install:
- pip install -r requirements.txt
- npm install
script:
- grunt deploy
after_success:
- bash deploy.sh

env:
  global:
    secure: tx4fGtZAo0lCdscJntByedsZyM6GgRfoDRFsQ7cxbSnevj3EVcMeKLp6JekMdjMP8LnvD7/h7HEFhxmOKU1HCN4utyrUcQcIuglQVqQaJJKpFV3T2t5FYwDvsGK5x4WDOx2+ncj5uJgcCEwj2P6W2m/Cs9aPx0Jy9dFlapUL0xIrJ2hpe5AgABkhEWzpI7+MgMmWxDTK59VROgCEyqHJolJoboXZ/GOCcvKGq9+QmF0SyBADsGxS9qKxmpryhcpMZ9QHumS9DBEa3mumMicnC80sUp/eqZlw1m1ooQ8Oc2aHsuGnqz/ucZlpWT2mdP7f7UU5FHhpEvZn9822sNYuD+bt0mxcP2tLSMaRiL1xaSnFcNengyuVF1WFohi0D2M+a3srH6C7WZ/joiaK+zUMl4Kha3QaUnM3vEr4XUoWfsIT3B618Vqw5EopqrzDXx59xihDghHlCs1D7hiA5gUpmIxLXGmfb+EzXPHgbWmCibJyM3nHpVNI4GgloWF4u3mfrYN9Pcqi3mNxy3E+BsT/NO0weqi9jRT/uQlFToTc/PQ4i8E+1Q4Vl9RX4q+gfwEMrXtIksOWaF1Ii7ZARk7cnBckHPc2z2YEq+LhtnYkVA4YU6+6PDbn/dcK277lW7jjzkuyjoATUxTR8TVRpnQWEb+FtDctjcNOfOrATeEN8xo=
